### ISSUE TITLE
我把项目启动起来，用你的地址访问404

### ISSUE THREAD

**Issue by doushuihai** [JoeyBling/SpringBoot_MyBatisPlus#2]

**Comment by JoeyBling** [comment]
> 项目访问路径：http://localhost:端口号/admin

**Comment by doushuihai** [comment]
你的server.contextPath配置wstro了  不改的话应该是http://localhost:端口号/wstro/admin 这样是可以的  谢谢老哥

**Comment by JoeyBling** [comment]
> 你的server.contextPath配置wstro了 不改的话应该是[http://localhost:端口号/wstro/admin](http://localhost:%E7%AB%AF%E5%8F%A3%E5%8F%B7/wstro/admin) 这样是可以的 谢谢老哥

对对对，不好意思啊，配置文件忘改了，谢谢你的支持

**Comment by JoeyBling** [comment]
> 你的server.contextPath配置wstro了 不改的话应该是[http://localhost:端口号/wstro/admin](http://localhost:%E7%AB%AF%E5%8F%A3%E5%8F%B7/wstro/admin) 这样是可以的 谢谢老哥

这个项目比较庞统些，如果你只是单独需要SpringBoot + Shiro + MyBatisPlus的话，我更推荐这个项目
> [https://github.com/JoeyBling/bootplus](https://github.com/JoeyBling/bootplus "基于SpringBoot + Shiro + MyBatisPlus的权限管理框架")

相对来说精简了许多

**Comment by doushuihai** [comment]
![image](https://user-images.githubusercontent.com/37564157/61920862-a8473800-af8d-11e9-8476-d0200de2a294.png)
老哥subject.login(token);这个方法没有看懂它是怎么去用户表验证账户密码的呢 我对shiro不是很懂
这句UsernamePasswordToken token = new UsernamePasswordToken(username, password);没看明白它有什么作用

**Comment by JoeyBling** [comment]
> ![image](https://user-images.githubusercontent.com/37564157/61920862-a8473800-af8d-11e9-8476-d0200de2a294.png)
> 老哥subject.login(token);这个方法没有看懂它是怎么去用户表验证账户密码的呢 我对shiro不是很懂
> 这句UsernamePasswordToken token = new UsernamePasswordToken(username, password);没看明白它有什么作用

这个是Shiro官方提供的验证类，我们只需要实现接口，做自己业务的封装就可以，然后登陆调用对应的方法即可实现，在`shiro`包下面封装了一些业务类，你可以去看看，关于Shiro如何实现的，我建议你上网查下Shiro相关的资料。
