### ISSUE TITLE
启动报错

### ISSUE THREAD

**Issue by kzdw** [JoeyBling/SpringBoot_MyBatisPlus#6]
本地没有redis，所以去掉了@Configuration启动报错，同时去掉@EnableCaching还是报错。

`"C:\Program Files (x86)\Java\jdk1.8.0_191\bin\java" -agentlib:jdwp=transport=dt_socket,address=127.0.0.1:52291,suspend=y,server=n -XX:TieredStopAtLevel=1 -noverify -Dspring.output.ansi.enabled=always -Dcom.sun.management.jmxremote -Dcom.sun.management.jmxremote.port=52290 -Dcom.sun.management.jmxremote.authenticate=false -Dcom.sun.management.jmxremote.ssl=false -Djava.rmi.server.hostname=localhost -Dspring.liveBeansView.mbeanDomain -Dspring.application.admin.enabled=true -javaagent:C:\Users\Administrator\.IntelliJIdea2017.3\system\captureAgent\debugger-agent.jar=C:\Users\Administrator\AppData\Local\Temp\capture826.props -Dfile.encoding=UTF-8 -classpath "C:\Program Files (x86)\Java\jdk1.8.0_191\jre\lib\charsets.jar;C:\Program Files (x86)\Java\jdk1.8.0_191\jre\lib\deploy.jar;C:\Program Files (x86)\Java\jdk1.8.0_191\jre\lib\ext\access-bridge-32.jar;C:\Program Files (x86)\Java\jdk1.8.0_191\jre\lib\ext\cldrdata.jar;C:\Program Files (x86)\Java\jdk1.8.0_191\jre\lib\ext\dnsns.jar;C:\Program Files (x86)\Java\jdk1.8.0_191\jre\lib\ext\jaccess.jar;C:\Program Files (x86)\Java\jdk1.8.0_191\jre\lib\ext\jfxrt.jar;C:\Program Files (x86)\Java\jdk1.8.0_191\jre\lib\ext\localedata.jar;C:\Program Files (x86)\Java\jdk1.8.0_191\jre\lib\ext\nashorn.jar;C:\Program Files (x86)\Java\jdk1.8.0_191\jre\lib\ext\sunec.jar;C:\Program Files (x86)\Java\jdk1.8.0_191\jre\lib\ext\sunjce_provider.jar;C:\Program Files (x86)\Java\jdk1.8.0_191\jre\lib\ext\sunmscapi.jar;C:\Program Files (x86)\Java\jdk1.8.0_191\jre\lib\ext\sunpkcs11.jar;C:\Program Files (x86)\Java\jdk1.8.0_191\jre\lib\ext\zipfs.jar;C:\Program Files (x86)\Java\jdk1.8.0_191\jre\lib\javaws.jar;C:\Program Files (x86)\Java\jdk1.8.0_191\jre\lib\jce.jar;C:\Program Files (x86)\Java\jdk1.8.0_191\jre\lib\jfr.jar;C:\Program Files (x86)\Java\jdk1.8.0_191\jre\lib\jfxswt.jar;C:\Program Files (x86)\Java\jdk1.8.0_191\jre\lib\jsse.jar;C:\Program Files (x86)\Java\jdk1.8.0_191\jre\lib\management-agent.jar;C:\Program Files (x86)\Java\jdk1.8.0_191\jre\lib\plugin.jar;C:\Program Files (x86)\Java\jdk1.8.0_191\jre\lib\resources.jar;C:\Program Files (x86)\Java\jdk1.8.0_191\jre\lib\rt.jar;F:\javaStudy\SpringBoot_MyBatisPlus-master\SpringBoot_MyBatisPlus-master\target\classes;C:\Users\Administrator\.m2\repository\org\springframework\boot\spring-boot-starter\1.5.1.RELEASE\spring-boot-starter-1.5.1.RELEASE.jar;C:\Users\Administrator\.m2\repository\org\springframework\boot\spring-boot\1.5.1.RELEASE\spring-boot-1.5.1.RELEASE.jar;C:\Users\Administrator\.m2\repository\org\springframework\boot\spring-boot-autoconfigure\1.5.1.RELEASE\spring-boot-autoconfigure-1.5.1.RELEASE.jar;C:\Users\Administrator\.m2\repository\org\springframework\spring-core\4.3.6.RELEASE\spring-core-4.3.6.RELEASE.jar;C:\Users\Administrator\.m2\repository\org\yaml\snakeyaml\1.17\snakeyaml-1.17.jar;C:\Users\Administrator\.m2\repository\io\gitee\zhousiwei\fastjson-spring-boot-starter\8.8.8.RELEASE\fastjson-spring-boot-starter-8.8.8.RELEASE.jar;C:\Users\Administrator\.m2\repository\net\mingsoft\shiro-freemarker-tags\0.1\shiro-freemarker-tags-0.1.jar;C:\Users\Administrator\.m2\repository\commons-codec\commons-codec\1.10\commons-codec-1.10.jar;C:\Users\Administrator\.m2\repository\log4j\log4j\1.2.17\log4j-1.2.17.jar;C:\Users\Administrator\.m2\repository\com\google\zxing\javase\3.1.0\javase-3.1.0.jar;C:\Users\Administrator\.m2\repository\com\google\zxing\core\3.1.0\core-3.1.0.jar;C:\Users\Administrator\.m2\repository\org\springframework\integration\spring-integration-mail\4.3.7.RELEASE\spring-integration-mail-4.3.7.RELEASE.jar;C:\Users\Administrator\.m2\repository\org\springframework\integration\spring-integration-core\4.3.7.RELEASE\spring-integration-core-4.3.7.RELEASE.jar;C:\Users\Administrator\.m2\repository\org\springframework\spring-messaging\4.3.6.RELEASE\spring-messaging-4.3.6.RELEASE.jar;C:\Users\Administrator\.m2\repository\org\springframework\retry\spring-retry\1.2.0.RELEASE\spring-retry-1.2.0.RELEASE.jar;C:\Users\Administrator\.m2\repository\net\sourceforge\jexcelapi\jxl\2.6.12\jxl-2.6.12.jar;C:\Users\Administrator\.m2\repository\com\sun\mail\javax.mail\1.5.6\javax.mail-1.5.6.jar;C:\Users\Administrator\.m2\repository\javax\activation\activation\1.1\activation-1.1.jar;C:\Users\Administrator\.m2\repository\com\mortennobel\java-image-scaling\0.8.6\java-image-scaling-0.8.6.jar;C:\Users\Administrator\.m2\repository\javax\servlet\javax.servlet-api\3.1.0\javax.servlet-api-3.1.0.jar;C:\Users\Administrator\.m2\repository\org\springframework\spring-context\4.3.6.RELEASE\spring-context-4.3.6.RELEASE.jar;C:\Users\Administrator\.m2\repository\org\springframework\spring-aop\4.3.6.RELEASE\spring-aop-4.3.6.RELEASE.jar;C:\Users\Administrator\.m2\repository\org\springframework\spring-expression\4.3.6.RELEASE\spring-expression-4.3.6.RELEASE.jar;C:\Users\Administrator\.m2\repository\org\springframework\spring-tx\4.3.6.RELEASE\spring-tx-4.3.6.RELEASE.jar;C:\Users\Administrator\.m2\repository\org\freemarker\freemarker\2.3.25-incubating\freemarker-2.3.25-incubating.jar;C:\Users\Administrator\.m2\repository\org\apache\shiro\shiro-all\1.2.4\shiro-all-1.2.4.jar;C:\Users\Administrator\.m2\repository\org\apache\shiro\shiro-guice\1.2.4\shiro-guice-1.2.4.jar;C:\Users\Administrator\.m2\repository\com\google\inject\guice\3.0\guice-3.0.jar;C:\Users\Administrator\.m2\repository\javax\inject\javax.inject\1\javax.inject-1.jar;C:\Users\Administrator\.m2\repository\aopalliance\aopalliance\1.0\aopalliance-1.0.jar;C:\Users\Administrator\.m2\repository\com\google\inject\extensions\guice-multibindings\3.0\guice-multibindings-3.0.jar;C:\Users\Administrator\.m2\repository\io\springfox\springfox-swagger2\2.6.1\springfox-swagger2-2.6.1.jar;C:\Users\Administrator\.m2\repository\io\swagger\swagger-annotations\1.5.10\swagger-annotations-1.5.10.jar;C:\Users\Administrator\.m2\repository\io\swagger\swagger-models\1.5.10\swagger-models-1.5.10.jar;C:\Users\Administrator\.m2\repository\com\fasterxml\jackson\core\jackson-annotations\2.8.0\jackson-annotations-2.8.0.jar;C:\Users\Administrator\.m2\repository\io\springfox\springfox-spi\2.6.1\springfox-spi-2.6.1.jar;C:\Users\Administrator\.m2\repository\io\springfox\springfox-core\2.6.1\springfox-core-2.6.1.jar;C:\Users\Administrator\.m2\repository\io\springfox\springfox-schema\2.6.1\springfox-schema-2.6.1.jar;C:\Users\Administrator\.m2\repository\io\springfox\springfox-swagger-common\2.6.1\springfox-swagger-common-2.6.1.jar;C:\Users\Administrator\.m2\repository\io\springfox\springfox-spring-web\2.6.1\springfox-spring-web-2.6.1.jar;C:\Users\Administrator\.m2\repository\com\google\guava\guava\18.0\guava-18.0.jar;C:\Users\Administrator\.m2\repository\com\fasterxml\classmate\1.3.3\classmate-1.3.3.jar;C:\Users\Administrator\.m2\repository\org\slf4j\slf4j-api\1.7.22\slf4j-api-1.7.22.jar;C:\Users\Administrator\.m2\repository\org\springframework\plugin\spring-plugin-core\1.2.0.RELEASE\spring-plugin-core-1.2.0.RELEASE.jar;C:\Users\Administrator\.m2\repository\org\springframework\plugin\spring-plugin-metadata\1.2.0.RELEASE\spring-plugin-metadata-1.2.0.RELEASE.jar;C:\Users\Administrator\.m2\repository\org\mapstruct\mapstruct\1.0.0.Final\mapstruct-1.0.0.Final.jar;C:\Users\Administrator\.m2\repository\io\springfox\springfox-swagger-ui\2.6.1\springfox-swagger-ui-2.6.1.jar;C:\Users\Administrator\.m2\repository\org\springframework\boot\spring-boot-starter-mail\1.5.1.RELEASE\spring-boot-starter-mail-1.5.1.RELEASE.jar;C:\Users\Administrator\.m2\repository\com\github\axet\kaptcha\0.0.9\kaptcha-0.0.9.jar;C:\Users\Administrator\.m2\repository\com\jhlabs\filters\2.0.235\filters-2.0.235.jar;C:\Users\Administrator\.m2\repository\net\coobird\thumbnailator\0.4.8\thumbnailator-0.4.8.jar;C:\Users\Administrator\.m2\repository\org\apache\commons\commons-lang3\3.3.2\commons-lang3-3.3.2.jar;C:\Users\Administrator\.m2\repository\commons-fileupload\commons-fileupload\1.3.1\commons-fileupload-1.3.1.jar;C:\Users\Administrator\.m2\repository\commons-io\commons-io\2.2\commons-io-2.2.jar;C:\Users\Administrator\.m2\repository\eu\bitwalker\UserAgentUtils\1.20\UserAgentUtils-1.20.jar;C:\Users\Administrator\.m2\repository\org\springframework\boot\spring-boot-starter-web\1.5.1.RELEASE\spring-boot-starter-web-1.5.1.RELEASE.jar;C:\Users\Administrator\.m2\repository\org\hibernate\hibernate-validator\5.3.4.Final\hibernate-validator-5.3.4.Final.jar;C:\Users\Administrator\.m2\repository\javax\validation\validation-api\1.1.0.Final\validation-api-1.1.0.Final.jar;C:\Users\Administrator\.m2\repository\org\jboss\logging\jboss-logging\3.3.0.Final\jboss-logging-3.3.0.Final.jar;C:\Users\Administrator\.m2\repository\com\fasterxml\jackson\core\jackson-databind\2.8.6\jackson-databind-2.8.6.jar;C:\Users\Administrator\.m2\repository\com\fasterxml\jackson\core\jackson-core\2.8.6\jackson-core-2.8.6.jar;C:\Users\Administrator\.m2\repository\org\springframework\spring-web\4.3.6.RELEASE\spring-web-4.3.6.RELEASE.jar;C:\Users\Administrator\.m2\repository\org\springframework\spring-webmvc\4.3.6.RELEASE\spring-webmvc-4.3.6.RELEASE.jar;C:\Users\Administrator\.m2\repository\org\springframework\boot\spring-boot-starter-data-jpa\1.5.1.RELEASE\spring-boot-starter-data-jpa-1.5.1.RELEASE.jar;C:\Users\Administrator\.m2\repository\org\springframework\boot\spring-boot-starter-aop\1.5.1.RELEASE\spring-boot-starter-aop-1.5.1.RELEASE.jar;C:\Users\Administrator\.m2\repository\org\aspectj\aspectjweaver\1.8.9\aspectjweaver-1.8.9.jar;C:\Users\Administrator\.m2\repository\org\springframework\boot\spring-boot-starter-jdbc\1.5.1.RELEASE\spring-boot-starter-jdbc-1.5.1.RELEASE.jar;C:\Users\Administrator\.m2\repository\org\apache\tomcat\tomcat-jdbc\8.5.11\tomcat-jdbc-8.5.11.jar;C:\Users\Administrator\.m2\repository\org\apache\tomcat\tomcat-juli\8.5.11\tomcat-juli-8.5.11.jar;C:\Users\Administrator\.m2\repository\org\springframework\spring-jdbc\4.3.6.RELEASE\spring-jdbc-4.3.6.RELEASE.jar;C:\Users\Administrator\.m2\repository\org\hibernate\hibernate-core\5.0.11.Final\hibernate-core-5.0.11.Final.jar;C:\Users\Administrator\.m2\repository\org\hibernate\javax\persistence\hibernate-jpa-2.1-api\1.0.0.Final\hibernate-jpa-2.1-api-1.0.0.Final.jar;C:\Users\Administrator\.m2\repository\org\javassist\javassist\3.21.0-GA\javassist-3.21.0-GA.jar;C:\Users\Administrator\.m2\repository\antlr\antlr\2.7.7\antlr-2.7.7.jar;C:\Users\Administrator\.m2\repository\org\jboss\jandex\2.0.0.Final\jandex-2.0.0.Final.jar;C:\Users\Administrator\.m2\repository\dom4j\dom4j\1.6.1\dom4j-1.6.1.jar;C:\Users\Administrator\.m2\repository\org\hibernate\common\hibernate-commons-annotations\5.0.1.Final\hibernate-commons-annotations-5.0.1.Final.jar;C:\Users\Administrator\.m2\repository\org\hibernate\hibernate-entitymanager\5.0.11.Final\hibernate-entitymanager-5.0.11.Final.jar;C:\Users\Administrator\.m2\repository\javax\transaction\javax.transaction-api\1.2\javax.transaction-api-1.2.jar;C:\Users\Administrator\.m2\repository\org\springframework\data\spring-data-jpa\1.11.0.RELEASE\spring-data-jpa-1.11.0.RELEASE.jar;C:\Users\Administrator\.m2\repository\org\springframework\data\spring-data-commons\1.13.0.RELEASE\spring-data-commons-1.13.0.RELEASE.jar;C:\Users\Administrator\.m2\repository\org\springframework\spring-orm\4.3.6.RELEASE\spring-orm-4.3.6.RELEASE.jar;C:\Users\Administrator\.m2\repository\org\springframework\spring-aspects\4.3.6.RELEASE\spring-aspects-4.3.6.RELEASE.jar;C:\Users\Administrator\.m2\repository\org\springframework\boot\spring-boot-starter-freemarker\1.5.1.RELEASE\spring-boot-starter-freemarker-1.5.1.RELEASE.jar;C:\Users\Administrator\.m2\repository\org\springframework\boot\spring-boot-starter-log4j\1.3.5.RELEASE\spring-boot-starter-log4j-1.3.5.RELEASE.jar;C:\Users\Administrator\.m2\repository\org\slf4j\jcl-over-slf4j\1.7.22\jcl-over-slf4j-1.7.22.jar;C:\Users\Administrator\.m2\repository\org\slf4j\jul-to-slf4j\1.7.22\jul-to-slf4j-1.7.22.jar;C:\Users\Administrator\.m2\repository\org\slf4j\slf4j-log4j12\1.7.22\slf4j-log4j12-1.7.22.jar;C:\Users\Administrator\.m2\repository\org\springframework\boot\spring-boot-starter-redis\1.3.3.RELEASE\spring-boot-starter-redis-1.3.3.RELEASE.jar;C:\Users\Administrator\.m2\repository\org\springframework\data\spring-data-redis\1.8.0.RELEASE\spring-data-redis-1.8.0.RELEASE.jar;C:\Users\Administrator\.m2\repository\org\springframework\data\spring-data-keyvalue\1.2.0.RELEASE\spring-data-keyvalue-1.2.0.RELEASE.jar;C:\Users\Administrator\.m2\repository\org\springframework\spring-oxm\4.3.6.RELEASE\spring-oxm-4.3.6.RELEASE.jar;C:\Users\Administrator\.m2\repository\com\vaadin\external\google\android-json\0.0.20131108.vaadin1\android-json-0.0.20131108.vaadin1.jar;C:\Users\Administrator\.m2\repository\org\quartz-scheduler\quartz\2.3.0\quartz-2.3.0.jar;C:\Users\Administrator\.m2\repository\com\mchange\c3p0\0.9.5.2\c3p0-0.9.5.2.jar;C:\Users\Administrator\.m2\repository\com\mchange\mchange-commons-java\0.2.11\mchange-commons-java-0.2.11.jar;C:\Users\Administrator\.m2\repository\com\zaxxer\HikariCP-java6\2.3.13\HikariCP-java6-2.3.13.jar;C:\Users\Administrator\.m2\repository\redis\clients\jedis\2.9.0\jedis-2.9.0.jar;C:\Users\Administrator\.m2\repository\org\apache\commons\commons-pool2\2.4.2\commons-pool2-2.4.2.jar;C:\Users\Administrator\.m2\repository\com\alibaba\druid\1.0.26\druid-1.0.26.jar;C:\Program Files (x86)\Java\jdk1.8.0_191\lib\jconsole.jar;C:\Program Files (x86)\Java\jdk1.8.0_191\lib\tools.jar;C:\Users\Administrator\.m2\repository\mysql\mysql-connector-java\5.1.40\mysql-connector-java-5.1.40.jar;C:\Users\Administrator\.m2\repository\com\alibaba\fastjson\1.2.15\fastjson-1.2.15.jar;C:\Users\Administrator\.m2\repository\com\baomidou\mybatisplus-spring-boot-starter\1.0.2\mybatisplus-spring-boot-starter-1.0.2.jar;C:\Users\Administrator\.m2\repository\org\springframework\boot\spring-boot-configuration-processor\1.5.1.RELEASE\spring-boot-configuration-processor-1.5.1.RELEASE.jar;C:\Users\Administrator\.m2\repository\com\baomidou\mybatis-plus\2.0.8\mybatis-plus-2.0.8.jar;C:\Users\Administrator\.m2\repository\org\mybatis\mybatis-spring\1.3.1\mybatis-spring-1.3.1.jar;C:\Users\Administrator\.m2\repository\org\mybatis\mybatis\3.4.4\mybatis-3.4.4.jar;C:\Users\Administrator\.m2\repository\org\apache\shiro\shiro-core\1.4.2\shiro-core-1.4.2.jar;C:\Users\Administrator\.m2\repository\org\apache\shiro\shiro-lang\1.4.2\shiro-lang-1.4.2.jar;C:\Users\Administrator\.m2\repository\org\apache\shiro\shiro-cache\1.4.2\shiro-cache-1.4.2.jar;C:\Users\Administrator\.m2\repository\org\apache\shiro\shiro-crypto-hash\1.4.2\shiro-crypto-hash-1.4.2.jar;C:\Users\Administrator\.m2\repository\org\apache\shiro\shiro-crypto-core\1.4.2\shiro-crypto-core-1.4.2.jar;C:\Users\Administrator\.m2\repository\org\apache\shiro\shiro-crypto-cipher\1.4.2\shiro-crypto-cipher-1.4.2.jar;C:\Users\Administrator\.m2\repository\org\apache\shiro\shiro-config-core\1.4.2\shiro-config-core-1.4.2.jar;C:\Users\Administrator\.m2\repository\org\apache\shiro\shiro-config-ogdl\1.4.2\shiro-config-ogdl-1.4.2.jar;C:\Users\Administrator\.m2\repository\commons-beanutils\commons-beanutils\1.9.3\commons-beanutils-1.9.3.jar;C:\Users\Administrator\.m2\repository\commons-collections\commons-collections\3.2.2\commons-collections-3.2.2.jar;C:\Users\Administrator\.m2\repository\org\apache\shiro\shiro-event\1.4.2\shiro-event-1.4.2.jar;C:\Users\Administrator\.m2\repository\org\apache\shiro\shiro-web\1.4.2\shiro-web-1.4.2.jar;C:\Users\Administrator\.m2\repository\org\apache\shiro\shiro-spring\1.4.2\shiro-spring-1.4.2.jar;C:\Users\Administrator\.m2\repository\org\apache\shiro\shiro-ehcache\1.4.2\shiro-ehcache-1.4.2.jar;C:\Users\Administrator\.m2\repository\net\sf\ehcache\ehcache-core\2.6.11\ehcache-core-2.6.11.jar;C:\Users\Administrator\.m2\repository\net\sf\ehcache\ehcache\2.10.3\ehcache-2.10.3.jar;C:\Users\Administrator\.m2\repository\org\springframework\spring-context-support\4.3.6.RELEASE\spring-context-support-4.3.6.RELEASE.jar;C:\Users\Administrator\.m2\repository\org\springframework\spring-beans\4.3.6.RELEASE\spring-beans-4.3.6.RELEASE.jar;C:\Users\Administrator\.m2\repository\org\projectlombok\lombok\1.16.12\lombok-1.16.12.jar;D:\Program Files\JetBrains\IntelliJ IDEA 2017.3.5\lib\idea_rt.jar" com.wstro.App
Connected to the target VM, address: '127.0.0.1:52291', transport: 'socket'
      ___           ___                       ___           ___
     /__/\         /  /\          ___        /  /\         /  /\
    _\_ \:\       /  /:/_        /  /\      /  /::\       /  /::\
   /__/\ \:\     /  /:/ /\      /  /:/     /  /:/\:\     /  /:/\:\
  _\_ \:\ \:\   /  /:/ /::\    /  /:/     /  /:/~/:/    /  /:/  \:\
 /__/\ \:\ \:\ /__/:/ /:/\:\  /  /::\    /__/:/ /:/___ /__/:/ \__\:\
 \  \:\ \:\/:/ \  \:\/:/~/:/ /__/:/\:\   \  \:\/:::::/ \  \:\ /  /:/
  \  \:\ \::/   \  \::/ /:/  \__\/  \:\   \  \::/~~~~   \  \:\  /:/
   \  \:\/:/     \__\/ /:/        \  \:\   \  \:\        \  \:\/:/
    \  \::/        /__/:/          \__\/    \  \:\        \  \::/
     \__\/         \__\/                     \__\/         \__\/

application.version: 
application.formatted-version:                         
spring-boot.version:1.5.1.RELEASE  
spring-boot.formatted-version: (v1.5.1.RELEASE)
[INFO][2020-05-12 11:48:25] [App:48] Starting App on SKY-20170924KYZ with PID 9008 (F:\javaStudy\SpringBoot_MyBatisPlus-master\SpringBoot_MyBatisPlus-master\target\classes started by Administrator in F:\javaStudy\SpringBoot_MyBatisPlus-master\SpringBoot_MyBatisPlus-master)
[DEBUG][2020-05-12 11:48:25] [App:51] Running with Spring Boot v1.5.1.RELEASE, Spring v4.3.6.RELEASE
[INFO][2020-05-12 11:48:25] [App:641] The following profiles are active: dev
[INFO][2020-05-12 11:48:25] [AnnotationConfigEmbeddedWebApplicationContext:582] Refreshing org.springframework.boot.context.embedded.AnnotationConfigEmbeddedWebApplicationContext@90516e: startup date [Tue May 12 11:48:25 CST 2020]; root of context hierarchy
[INFO][2020-05-12 11:48:25] [Version:30] HV000001: Hibernate Validator 5.3.4.Final
[INFO][2020-05-12 11:48:26] [RepositoryConfigurationDelegate:165] Multiple Spring Data modules found, entering strict repository configuration mode!
[INFO][2020-05-12 11:48:26] [RepositoryConfigurationDelegate:165] Multiple Spring Data modules found, entering strict repository configuration mode!
[INFO][2020-05-12 11:48:26] [PropertiesFactoryBean:172] Loading properties file from URL [jar:file:/C:/Users/Administrator/.m2/repository/org/springframework/integration/spring-integration-core/4.3.7.RELEASE/spring-integration-core-4.3.7.RELEASE.jar!/META-INF/spring.integration.default.properties]
[INFO][2020-05-12 11:48:26] [IntegrationRegistrar:330] No bean named 'integrationHeaderChannelRegistry' has been explicitly defined. Therefore, a default DefaultHeaderChannelRegistry will be created.
[INFO][2020-05-12 11:48:26] [DefaultConfiguringBeanFactoryPostProcessor:130] No bean named 'errorChannel' has been explicitly defined. Therefore, a default PublishSubscribeChannel will be created.
[INFO][2020-05-12 11:48:26] [DefaultConfiguringBeanFactoryPostProcessor:158] No bean named 'taskScheduler' has been explicitly defined. Therefore, a default ThreadPoolTaskScheduler will be created.
[INFO][2020-05-12 11:48:26] [AutowiredAnnotationBeanPostProcessor:155] JSR-330 'javax.inject.Inject' annotation found and supported for autowiring
[INFO][2020-05-12 11:48:26] [PostProcessorRegistrationDelegate$BeanPostProcessorChecker:325] Bean 'org.springframework.boot.autoconfigure.validation.ValidationAutoConfiguration' of type [class org.springframework.boot.autoconfigure.validation.ValidationAutoConfiguration] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
[WARN][2020-05-12 11:48:26] [ParameterMessageInterpolator:28] HV000184: ParameterMessageInterpolator has been chosen, EL interpolation will not be supported
[INFO][2020-05-12 11:48:27] [PostProcessorRegistrationDelegate$BeanPostProcessorChecker:325] Bean 'validator' of type [class org.springframework.validation.beanvalidation.LocalValidatorFactoryBean] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
[INFO][2020-05-12 11:48:27] [PostProcessorRegistrationDelegate$BeanPostProcessorChecker:325] Bean 'shiroConfiguration' of type [class com.wstro.config.ShiroConfiguration$$EnhancerBySpringCGLIB$$b7e4ea41] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
[INFO][2020-05-12 11:48:27] [PostProcessorRegistrationDelegate$BeanPostProcessorChecker:325] Bean 'getUserRealm' of type [class com.wstro.shiro.UserRealm] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
[INFO][2020-05-12 11:48:27] [ShiroConfiguration$$EnhancerBySpringCGLIB$$b7e4ea41:122] ShiroConfiguration.getEhCacheManager()
[INFO][2020-05-12 11:48:27] [PostProcessorRegistrationDelegate$BeanPostProcessorChecker:325] Bean 'ehCacheManager' of type [class org.apache.shiro.cache.ehcache.EhCacheManager] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
[INFO][2020-05-12 11:48:27] [EhCacheManager:159] Cache with name 'com.wstro.shiro.UserRealm.authorizationCache' does not yet exist.  Creating now.
[INFO][2020-05-12 11:48:27] [EhCacheManager:166] Added EhCache named [com.wstro.shiro.UserRealm.authorizationCache]
[INFO][2020-05-12 11:48:27] [ShiroConfiguration$$EnhancerBySpringCGLIB$$b7e4ea41:150] ShiroConfiguration.rememberMeManager()
[INFO][2020-05-12 11:48:27] [ShiroConfiguration$$EnhancerBySpringCGLIB$$b7e4ea41:135] ShiroConfiguration.rememberMeCookie()
[INFO][2020-05-12 11:48:27] [PostProcessorRegistrationDelegate$BeanPostProcessorChecker:325] Bean 'rememberMeCookie' of type [class org.apache.shiro.web.servlet.SimpleCookie] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
[INFO][2020-05-12 11:48:27] [PostProcessorRegistrationDelegate$BeanPostProcessorChecker:325] Bean 'rememberMeManager' of type [class org.apache.shiro.web.mgt.CookieRememberMeManager] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
[INFO][2020-05-12 11:48:27] [PostProcessorRegistrationDelegate$BeanPostProcessorChecker:325] Bean 'securityManager' of type [class org.apache.shiro.web.mgt.DefaultWebSecurityManager] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
[INFO][2020-05-12 11:48:27] [PostProcessorRegistrationDelegate$BeanPostProcessorChecker:325] Bean 'authorizationAttributeSourceAdvisor' of type [class org.apache.shiro.spring.security.interceptor.AuthorizationAttributeSourceAdvisor] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
[INFO][2020-05-12 11:48:27] [PostProcessorRegistrationDelegate$BeanPostProcessorChecker:325] Bean 'org.springframework.cache.annotation.ProxyCachingConfiguration' of type [class org.springframework.cache.annotation.ProxyCachingConfiguration$$EnhancerBySpringCGLIB$$dc28ad8f] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
[INFO][2020-05-12 11:48:27] [PostProcessorRegistrationDelegate$BeanPostProcessorChecker:325] Bean 'org.springframework.transaction.annotation.ProxyTransactionManagementConfiguration' of type [class org.springframework.transaction.annotation.ProxyTransactionManagementConfiguration$$EnhancerBySpringCGLIB$$93167771] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
[INFO][2020-05-12 11:48:27] [ShiroConfiguration$$EnhancerBySpringCGLIB$$b7e4ea41:42] ShiroConfiguration.shiroFilter()
[INFO][2020-05-12 11:48:27] [PropertiesFactoryBean:172] Loading properties file from URL [jar:file:/C:/Users/Administrator/.m2/repository/org/springframework/integration/spring-integration-core/4.3.7.RELEASE/spring-integration-core-4.3.7.RELEASE.jar!/META-INF/spring.integration.default.properties]
[INFO][2020-05-12 11:48:27] [PostProcessorRegistrationDelegate$BeanPostProcessorChecker:325] Bean 'integrationGlobalProperties' of type [class org.springframework.beans.factory.config.PropertiesFactoryBean] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
[INFO][2020-05-12 11:48:27] [PostProcessorRegistrationDelegate$BeanPostProcessorChecker:325] Bean 'integrationGlobalProperties' of type [class java.util.Properties] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
[WARN][2020-05-12 11:48:28] [AnnotationConfigEmbeddedWebApplicationContext:550] Exception encountered during context initialization - cancelling refresh attempt: org.springframework.context.ApplicationContextException: Unable to start embedded container; nested exception is org.springframework.context.ApplicationContextException: Unable to start EmbeddedWebApplicationContext due to missing EmbeddedServletContainerFactory bean.
[ERROR][2020-05-12 11:48:28] [SpringApplication:815] Application startup failed
org.springframework.context.ApplicationContextException: Unable to start embedded container; nested exception is org.springframework.context.ApplicationContextException: Unable to start EmbeddedWebApplicationContext due to missing EmbeddedServletContainerFactory bean.
	at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.onRefresh(EmbeddedWebApplicationContext.java:137)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:536)
	at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.refresh(EmbeddedWebApplicationContext.java:122)
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:737)
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:370)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:314)
	at com.wstro.App.main(App.java:30)
Caused by: org.springframework.context.ApplicationContextException: Unable to start EmbeddedWebApplicationContext due to missing EmbeddedServletContainerFactory bean.
	at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.getEmbeddedServletContainerFactory(EmbeddedWebApplicationContext.java:189)
	at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.createEmbeddedServletContainer(EmbeddedWebApplicationContext.java:162)
	at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.onRefresh(EmbeddedWebApplicationContext.java:134)
	... 6 more
Disconnected from the target VM, address: '127.0.0.1:52291', transport: 'socket'

Process finished with exit code 1
`

**Comment by JoeyBling** [comment]
mvn引起的缘故，参考我的文章
> [SpringBoot依赖scope为provided时，IDEA运行报错](https://www.jianshu.com/p/7bbeb663f1c9)

**Comment by kzdw** [comment]
果然如此，问题已经解决！
